export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GGL_ID_FETCH_SUCCESS = 'GGL_ID_FETCH_SUCCESS';
export const MEMBER_AUTH_LOGOUT = 'MEMBER_AUTH_LOGOUT';
export const MEM_AUTH_SUCCESS = 'MEM_AUTH_SUCCESS';

export const GGL_LOAD_SUCCESS = 'GGL_LOAD_SUCCESS';
export const GGL_LOAD_START = 'GGL_LOAD_START';
export const GGL_LOAD_FINISH = 'GGL_LOAD_FINISH';
export const SET_CURRENT_CLASS = 'SET_CURRENT_CLASS';
export const SET_CURRENT_BELT = 'SET_CURRENT_BELT';
export const UPDATE_PERSONS_WITH_CLASS_ATTENDER =
   'UPDATE_PERSONS_WITH_CLASS_ATTENDER';
export const GGL_SAVE_START = 'GGL_SAVE_START';
export const GGL_SAVE_FINISH = 'GGL_SAVE_FINISH';
export const ADD_TO_CLASS_ATTENDER = 'ADD_TO_CLASS_ATTENDER';
export const REMOVE_FROM_CLASS_ATTENDER = 'REMOVE_FROM_CLASS_ATTENDER';
export const GGL_LOGOUT = 'GGL_LOGOUT';
export const RESET_CURRCLASS = 'RESET_CURRCLASS';

export const STAT_LOAD_SUCCESS = 'STAT_LOAD_SUCCESS';
export const STAT_LOAD_START = 'STAT_LOAD_START';
export const STAT_LOAD_FINISH = 'STAT_LOAD_FINISH';
export const STAT_SAVE_START = 'STAT_SAVE_START';
export const STAT_SAVE_FINISH = 'STAT_SAVE_FINISH';
export const SET_CURRENT_ACTIVITY = 'SET_CURRENT_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const SET_DAILY_STAT = 'SET_DAILY_STAT';
export const STAT_LOGOUT = 'STAT_LOGOUT';
export const INIT_ACTIVITY = 'INIT_ACTIVITY';